# Generated by Django 2.2.1 on 2021-07-17 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210717_1351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('title',)},
        ),
        migrations.AlterModelOptions(
            name='bookcopy',
            options={},
        ),
    ]
