# Generated by Django 2.2.1 on 2021-07-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210717_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='numreviews',
            field=models.IntegerField(default=0),
        ),
    ]
