# Generated by Django 2.2.1 on 2021-07-19 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210719_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='num_of_reviews',
            new_name='number_of_reviews',
        ),
    ]
