# Generated by Django 2.2.1 on 2021-07-22 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_book_number_of_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratingsystem',
            name='is_rated',
        ),
    ]
